site_name: shadowquic
site_description: A 0-RTT QUIC proxy with SNI camouflage
site_url: https://spongebob888.github.io/shadowquic/
repo_url: https://github.com/spongebob888/shadowquic
repo_name: spongebob888/shadowquic
edit_uri: ""

docs_dir: docs

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.indexes
    - content.code.copy
    - content.code.annotate
    - search.suggest
    - search.highlight
    - toc.follow
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - md_in_html
  - tables
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

# >>> generated nav
nav:
  - Home: index.md
  - Configuration:
      - Overview: configuration/index.md
      - Inbound:
          - Overview: configuration/inbound/index.md
          - SOCKS5 server: configuration/inbound/socks.md
          - ShadowQuic server: configuration/inbound/shadowquic.md
          - SunnyQuic server: configuration/inbound/sunnyquic.md
      - Outbound:
          - Overview: configuration/outbound/index.md
          - SOCKS5 outbound: configuration/outbound/socks.md
          - ShadowQuic outbound: configuration/outbound/shadowquic.md
          - SunnyQuic outbound: configuration/outbound/sunnyquic.md
          - Direct outbound: configuration/outbound/direct.md
      - Shared types:
          - User authentication: configuration/shared/authuser.md
          - JLS upstream: configuration/shared/jlsupstream.md
          - Congestion control: configuration/shared/congestioncontrol.md
          - Brutal parameters: configuration/shared/brutalparams.md
          - Cipher suite preference: configuration/shared/ciphersuitepreference.md
          - DNS strategy: configuration/shared/dnsstrategy.md
          - Log level: configuration/shared/loglevel.md
# <<< generated nav
