[target.aarch64-unknown-linux-musl]
# https://github.com/mlua-rs/mlua/issues/724
rustflags = ["-C", "default-linker-libraries"]

[target.aarch64-linux-android]
  rustflags = ["-C", "default-linker-libraries"]

[target.armv7-linux-androideabi]
  rustflags = ["-C", "default-linker-libraries"]

[target.armv7-unknown-linux-musleabi]
  rustflags = ["-C", "default-linker-libraries"]

[target.armv7-unknown-linux-musleabihf]
  rustflags = ["-C", "default-linker-libraries"]