use std::sync::Arc;

use crate::msgs::squic::{SUNNY_QUIC_AUTH_LEN, SunnyCredential};

#[cfg(feature = "sunnyquic-gm-quic")]
mod gm_quic_wrapper;
pub mod inbound;
pub mod outbound;

#[cfg(feature = "sunnyquic-gm-quic")]
pub use gm_quic_wrapper::{Connection, EndClient, EndServer};

#[cfg(feature = "sunnyquic-iroh-quinn")]
mod iroh_wrapper;
#[cfg(feature = "sunnyquic-iroh-quinn")]
pub use iroh_wrapper::{Connection, EndClient, EndServer};

/// Generate sunnyquic user hash from username and password
/// The hash is generated by SHA256(username:password)
pub fn gen_sunny_user_hash(username: &str, password: &str) -> SunnyCredential {
    let hash_in = username.to_string() + ":" + password;
    let hash_out = ring::digest::digest(&ring::digest::SHA256, hash_in.into_bytes().as_ref());
    let mut arr = [0u8; SUNNY_QUIC_AUTH_LEN];
    let hash_bytes = hash_out.as_ref();
    let len = arr.len().min(hash_bytes.len());
    arr[..len].copy_from_slice(&hash_bytes[..len]);
    Arc::new(arr)
}
