name: Cargo Build & Test

on:
  push:
  pull_request:

env: 
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Rust project - latest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          nix develop --command \
            rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: |
          nix develop --command \
            rustup component add rustfmt
          nix develop --command \
            cargo fmt --check --verbose
      - run: |
          nix develop --command \
            cargo build --verbose
      - run: |
          nix develop --command \
            cargo test --release --verbose
      - run: |
          nix develop --command \
            uv run ./scripts/main_test.py 

  